# Generated by Django 2.2.19 on 2022-04-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220424_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.SlugField(unique=True),
        ),
    ]
